### ISSUE TITLE
0.2.x Todo List

### ISSUE THREAD

**Issue by ssnepenthe** [ssnepenthe/soter#1]
- [ ] More descriptive output, adjustable via verbosity flags.
- [x] ~~Basic validation on config values.~~
- [ ] Better handling of non-200 response codes.
- [x] ~~Some phpcs love.~~
- [x] ~~Update readme.~~
