### ISSUE TITLE
0.3.x todo list

### ISSUE THREAD

**Issue by ssnepenthe** [ssnepenthe/soter#2]
- [ ] Multisite - test and update as necessary to work in multisite.
- [ ] Add link to settings page in plugin_action_links?
- [ ] Re-run checker after plugin/theme/core update.
  - [ ] Consider how to handle when updates are done outside of wp-admin (composer, manually uploading, etc.)
- [ ] Should the abbreviated (x vulnerabilities detected) admin notice be dismissable?
- [x] Is there any reason to make other formatters for WP-CLI (json and yaml)?
- [x] The 12 hour response cache + 12 hour cron schedule likely means that packages are only truly being checked every 24 hours. Verify and adjust as necessary.
- [ ] Add an `ignore` flag and an `email` flag to the WP-CLI commands.
- [x] Switch to transient caching?
- [x] User agent used by WPClient.php should be site specific.
- [x] In results class - don't store prepared meta in DB - prepare it on the fly.
- [x] Add progress bar to wp-cli check-site command
